name: Trollmode
version: '1.0.3'
author: Professor_Sam
main: com.github.professorSam.trollmode.main.Main
commands: 
   trollmode:
      description: aktiviert den Trollmode
      permission: trollmode.use
permissions: 
   trollmode.use:
      default: false